matrix:
  include:
    - language: node_js
      node_js:
      - "stable"
      before_install:
        - stty cols 80
      
      
      dist: trusty
      sudo: required

      addons:
        firefox: latest
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable fluxbox

      before_script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3
        - fluxbox >/dev/null 2>&1 &
      
      cache:
        directories:
           - "node_modules"
      
      script:
        - npm run lint
        - npm run test-mocha
        - npm run browser-test
      
    - language: ruby
      rvm:
        - 2.2.0
     
      before_install: gem install bundler      
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - bundle exec rspec
        - npm run lint
        - npm run test-mocha
        - npm run browser-test
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

