env:
  global:
    - CC_TEST_REPORTER_ID=56b4d0bd7e39c085bacccf8b63492ace01b88f1032c1853737145fc658290c27
matrix:
  include:
    - language: node_js
      node_js:
      - "stable"
      before_install:
        - stty cols 80

      dist: trusty
      sudo: required

      addons:
        code_climate:
          repo_token: 56b4d0bd7e39c085bacccf8b63492ace01b88f1032c1853737145fc658290c27
        firefox: latest-beta
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable fluxbox

      before_script:
        - npm install codeclimate-test-reporter
        - npm install -g gulp-cli
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3
        - fluxbox >/dev/null 2>&1 &

      after_script:
        - codeclimate-test-reporter < ./coverage/lcov.info

      cache:
        directories:
           - "node_modules"

      script:
        - gulp
        - npm run lint
        - npm run raw-test
        - npm run port-test     
        - npm run docs:build
      
 #  - language: ruby
 #     rvm:
 #      - 2.2.0
 #
 #     install:
 #       - bundle install
 #     before_script:
 #       - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 #       - chmod +x ./cc-test-reporter
 #       - ./cc-test-reporter before-build
 #     script:
 #       - bundle exec rspec
 #     after_script:
 #       - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
