language: node_js
node_js:
  - "stable"
before_install:
  - stty cols 80

env:
  global:
    - CC_TEST_REPORTER_ID=56b4d0bd7e39c085bacccf8b63492ace01b88f1032c1853737145fc658290c27
dist: trusty
sudo: required

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable fluxbox

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

cache:
  directories:
    - "node_modules"

script:
  - bundle exec rspec
  - npm run lint
  - npm run test-mocha
  - npm run browser-test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  
 
after_success: gulp
